# Generated by Django 5.0.1 on 2025-01-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legislation",
            name="admin_department",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Administering department"
            ),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="administering_body",
            field=models.CharField(
                blank=True,
                help_text="Previously 'pe' in Excel",
                max_length=200,
                verbose_name="Administering Body",
            ),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="business_owner",
            field=models.CharField(
                max_length=200, verbose_name="Process / Business Owner"
            ),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="compliance_owner",
            field=models.CharField(max_length=200, verbose_name="Compliance Owner"),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="tier",
            field=models.CharField(
                choices=[
                    ("1", "Tier 1"),
                    ("2", "Tier 2"),
                    ("3H", "Tier 3 High"),
                    ("3L", "Tier 3 Low"),
                ],
                db_index=True,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="legislation",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Obligation"),
        ),
        migrations.AddIndex(
            model_name="legislation",
            index=models.Index(
                fields=["tier", "jurisdiction"], name="legislation_tier_a96c65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legislation",
            index=models.Index(fields=["title"], name="legislation_title_e8aabb_idx"),
        ),
    ]
